server:
  port: 8888
eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetchRegistry: false
ribbon:
  eureka:
    enabled: true
spring:
  application:
    name: CLOUD-PAYMENT-SERVICE